Add preferred layout name for new product page
Voog/design-boulder pull request #147
Opened 2021-03-18 08:55 UTC by robertpih

Related to #146

2021-05-19 08:59 UTC, siimha approved these changes

2021-05-19 13:27 UTC, siimha requested changes
[Siin](https://github.com/Voog/design-boulder/blob/master/components/menu-level-2.tpl#L20) ka veel puudu, aga title jäta samaks.

2021-05-20 11:53 UTC, siimha commented on components/add-page-button.tpl
> +<li class="{{ _wrapperClassName }}">
Kontrolli, kas `_wrapperClassName` on olemas `<li{% if _wrapperClassName != blank %} class="{{ _wrapperClassName }}"{% endif %} >`

2021-05-20 11:55 UTC, siimha commented on components/add-page-button.tpl
> +{%- endif -%}
Pane siia ikka igaks juhuks `else` ka:
```
{%- else -%}
  {%- assign add_product_label = '' -%}
  {%- assign add_product_title = '' -%}
{%- endif -%}
```

2021-05-21 07:26 UTC, siimha requested changes

2021-05-21 07:26 UTC, siimha commented on components/menu-level-2.tpl
> +              <li class="edy-btn">{% menuadd parent="item" %}</li>
Võid siin ka siis juba seda komponenti kasutada ja ei pea eraldi tääge kasutama. Hetkel on parent siin string.

2021-05-21 08:41 UTC, siimha commented on components/menu-breadcrumbs.tpl
> +        {% include 'add-page-button', _menuItem: site.root_item, _isAddProductTitle: true, _wrapperClassName: wrapperClass %}
Siin võid kasutada ka stringina` _wrapperClassName: 'menu-item menu-item-cms'` ja ei pea eelnevalt assainima.

2021-05-21 09:56 UTC, robertpih commented on components/menu-breadcrumbs.tpl
> +        {% include 'add-page-button', _menuItem: site.root_item, _isAddProductTitle: true, _wrapperClassName: wrapperClass %}
Eee. Backendile ei meeldi tühikud.

2021-05-21 09:58 UTC, tanelj requested changes

2021-05-21 09:58 UTC, tanelj commented on components/submenu-for-current.tpl
> +      {% if exclude_products == true and level2.layout_title != 'Product' %}
Kui juba siin ümber teha siis:

* Kasutaks `'Product'` asemel malli olemasolevat muutujat`product_layout`
* `exclude_products` - tundub, et selle muutujaga siin arvestamine ei ole vajalik, sest hetkel on igal pool, kus `submenu-for-current` include'itakse lisatud `exclude_products: true`

2021-05-21 10:05 UTC, tanelj commented on components/menu-breadcrumbs.tpl
> +        {% include 'add-page-button', _menuItem: site.root_item, _isAddProductTitle: true, _wrapperClassName: wrapperClass %}
tegelikult meeldivad ja siin toetatud.

2021-05-24 08:10 UTC, tanelj approved these changes

2021-05-24 13:48 UTC, siimha approved these changes
Naiss!

2021-05-25 08:55 UTC, merged