Add auto-rendered product layout
Voog/design-boulder pull request #149
Opened 2022-02-07 09:34 UTC by PeeterPaal

Adds auto-rendered product layout.
Also adds a browser hack to enhance image rendering in Chrome based browsers.
Closes #148

2022-02-07 14:55 UTC, tanelj approved these changes
Nice work!

2022-02-09 10:10 UTC, pxska approved these changes
👍🏻

2022-02-10 12:16 UTC, tanelj requested changes
Nice work and works as expected only one JS error:

* [ ] `BgPicker's `el` parameter has to be either a plain DOM node or a jQuery object around a DOM node.` since there has no BG bicker on the page. `Edicy.BgPicker()`, requires first parameter to be present. https://github.com/Edicy/design-boulder/blob/ee52eb67fe2ac4e2227daaa8bd5452cd0e11023c/components/edicy-tools.tpl#L30

2022-02-10 13:34 UTC, pxska commented on javascripts/global-application.js
> +        if ($(window).width() < 600) {
This value should be a bit higher (`< 641` looks correct)

2022-02-10 13:34 UTC, pxska approved these changes

2022-02-10 20:36 UTC, merged